spring:
  application:
    name: spring-and-spring-boot
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:iabdinur
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
server:
  error:
    include-message: always
    include-binding-errors: always
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: '*'

